In [1]:
import numpy as np


In [2]:
a=np.array([11,22,33,44,55])
a

array([11, 22, 33, 44, 55])

In [3]:
np.arange(1,100,11)

array([ 1, 12, 23, 34, 45, 56, 67, 78, 89])

In [4]:
#linspace------- function generates evenly spaced numbers over a specified interval

In [5]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [6]:
#zeros()----- function (from the NumPy library) is used to create an array filled entirely with zeros.
#It’s useful for initializing arrays before filling them with actual data, especially in numerical computations, image processing, and machine learning

np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [7]:
#ones()----- function is provided by NumPy to create an array filled entirely with the value 1.
#It’s useful for initializing arrays for mathematical operations, machine learning models, or placeholders in algorithms.

np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
#eye----- function is commonly used in numerical computing to create identity matrices.
#An identity matrix is a square matrix with ones on its main diagonal and zeros elsewhere. 
#This function is available in both MATLAB and NumPy (Python's numerical library), with slight differences in syntax and features.

np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
#Python Random randint
#randint()----function in Python is used to generate a random integer within a specified inclusive range.
#It is part of the random module

np.random.rand(2,3)

array([[0.86544662, 0.3057173 , 0.45121635],
       [0.53109475, 0.65178645, 0.61116403]])

In [10]:
np.random.randint(2,2000)

1450

In [11]:
[np.random.randint(2,66) for _ in range(5)]


[10, 10, 58, 52, 55]

In [12]:
#for one dimension
[np.random.randint(2,66) for _ in range(5)]
#for 2 *3 dimension
np.random.randint(2,66,size=(2,3))

array([[30, 41,  6],
       [13, 13, 23]], dtype=int32)

In [13]:
#shape ----shape tells you the size of an array in each dimension.---array.shape → returns a tuple
a.shape

(5,)

In [14]:
#b.ndim ----- gives the number of dimensions,
#b.shape ----- gives rows and columns,
#b.size ----- gives total elements, 
#b.dtype ----- gives the data type of the array.
b=np.array([[1,2,3,4,5,6],[6,9,7,8,9,10]])
print(b)
print(b.ndim)
print(b.shape)
print(b.size)
b.dtype

[[ 1  2  3  4  5  6]
 [ 6  9  7  8  9 10]]
2
(2, 6)
12


dtype('int64')

In [15]:
print(b.reshape(3,4))
print(b.reshape(1,-1))
b.reshape(-1,2)

[[ 1  2  3  4]
 [ 5  6  6  9]
 [ 7  8  9 10]]
[[ 1  2  3  4  5  6  6  9  7  8  9 10]]


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 6,  9],
       [ 7,  8],
       [ 9, 10]])

In [16]:
print(b.flatten())
b[0]=0

[ 1  2  3  4  5  6  6  9  7  8  9 10]


In [17]:
print(b.ravel())
b[0][1]=0

[ 0  0  0  0  0  0  6  9  7  8  9 10]


In [18]:
c1=np.array([[2,3],[4,5]])
d1=c1.ravel()
c1[0]=0
print(c1)
print(d1)

[[0 0]
 [4 5]]
[0 0 4 5]


In [19]:
c=np.array([[2,3],[4,5]])
d=c.flatten()
c[0]=0
print(c)
print(d)

[[0 0]
 [4 5]]
[2 3 4 5]


In [20]:
e=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(e[1][0][1])
print(e[0][1][1])
print(e[1][1][1])

10
6
14


In [21]:
#indexing---- selects all blocks (:) and the second row (1) from each block.
e[:,1]

array([[ 5,  6,  7,  8],
       [13, 14, 15, 16]])

In [22]:
#slice---- from index 1 up to (but not including) 4 along the first axis. 
#Since the first axis only has indices 0 and 1, this just returns

e[1:4]

array([[[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [23]:
#boolean flitering
e[e>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [24]:

arr = np.random.randint(1, 60, size=(3, 4, 5))
print(arr)


[[[12 54  6 44 15]
  [28 59 58 18 58]
  [47 31 59 35  7]
  [30 34 34 57 17]]

 [[11 26 43 29 30]
  [58 44 55 26 26]
  [32 51  1 32 25]
  [27 22 39 18  4]]

 [[11 27 17 56 24]
  [54 56 56 31 13]
  [10 51 30 50 54]
  [20 53 52 17 36]]]


In [25]:
sa=np.array([[1,2,3],[4,5,6]])
sa

array([[1, 2, 3],
       [4, 5, 6]])

np.std(sa)

In [26]:
np.mean(sa)
print(np.var(sa))
print(np.median(sa))
print(np.min(sa))
print(np.max(sa))

print(np.sum(sa))
print(np.sum(sa,axis=0))
print(np.sum(sa,axis=1))

2.9166666666666665
3.5
1
6
21
[5 7 9]
[ 6 15]


In [27]:
#print(np.percentile(sa))

In [28]:
np.random.seed(42)
np.random.normal(3,1)

3.496714153011233

In [29]:
np.argsort(sa)

array([[0, 1, 2],
       [0, 1, 2]])

In [30]:
np.absolute(sa)

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
np.vstack(sa)
np.hstack(sa)
#casting

array([1, 2, 3, 4, 5, 6])

In [32]:
np.sin(sa)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [33]:
np.cos(sa)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [34]:
ar=np.array([[1,2,3],[4,5,6]])
b=[2.0,3.0,5.0]
result=ar*b
result

array([[ 2.,  6., 15.],
       [ 8., 15., 30.]])

In [35]:
#broadcasting
arr=np.array([[1,2,3],[4,5,6]])
b=2.0
result=arr*b
result

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [91]:
df.to_csv(r"C:\Users\srima\OneDrive\Desktop\titanic_duo.csv")
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex  Age  SibSp  \
0                              Braund, Mr. Owen Harris    male   22      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female   38      1   
2                               Heikkinen, Miss. Laina  female   26      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   35      1   
4                             Allen, Mr. William Henry    male   35      0   
..                                                 ...     ...  ...    ...   
886                              Montvila, Rev. Juozas    male   27      0   
887                       Graham, Miss. Margaret Edith  female   19      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   29      1   
889                              Behr, Mr. Karl Howell    male   26      0   
890                                Dooley, Mr. Patrick    male   32      0   

     Parch            Ticket     Fare  female   male  
0        0         A/5 21171   7.2500   False   True  
1        0          PC 17599  71.2833    True  False  
2        0  STON/O2. 3101282   7.9250    True  False  
3        0            113803  53.1000    True  False  
4        0            373450   8.0500   False   True  
..     ...               ...      ...     ...    ...  
886      0            211536  13.0000   False   True  
887      0            112053  30.0000    True  False  
888      2        W./C. 6607  23.4500    True  False  
889      0            111369  30.0000   False   True  
890      0            370376   7.7500   False   True  

[891 rows x 12 columns]