In [ ]:
Create a NumPy array with values from 1 to 20.
Create a 5×5 matrix filled with zeros.
Create a 4×4 identity matrix.
Generate 15 random integers between 10 and 100.
Find the shape, size, and datatype of an array.
Reshape a 1D array of 24 elements into a 4×6 matrix.
Convert a 2D array into a 1D array.
Create an array containing only even numbers from 1 to 50.
Create an array containing multiples of 5 from 0 to 100.
Find the maximum and minimum value in an array.
Find the index position of the largest element.
Sort an array in ascending order.
Reverse an array without using loops.
Perform element-wise addition of two arrays.
Perform subtraction, multiplication, and division on arrays.
Find the mean, median, and standard deviation of an array.
Find the sum of all rows and columns in a matrix.
Multiply two matrices using NumPy.
Find the transpose of a matrix.
Find the determinant of a matrix.

In [2]:
#Create a NumPy array with values from 1 to 20.
import numpy as np
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [8]:
#Create a 5×5 matrix filled with zeros.
b=np.zeros((5,5))
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
#Create a 4×4 identity matrix.
c=np.identity(4)
c

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
#Generate 15 random integers between 10 and 100.
d=np.random.randint(10,100,15)
d

array([33, 18, 42, 35, 29, 16, 35, 13, 49, 98, 87, 51, 33, 57, 88],
      dtype=int32)

In [19]:
#Find the shape, size, and datatype of an array
print(d.shape)
print(d.size)
print(d.dtype)

(15,)
15
int32


In [23]:
#Reshape a 1D array of 24 elements into a 4×6 matrix.
e=np.arange(1,25)
e1=e.reshape(4,6)
e1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [26]:
#Convert a 2D array into a 1D array.
f=np.array([[1,2,3],[4,5,6]])
f1=f.ravel()
f1

array([1, 2, 3, 4, 5, 6])

In [31]:
#Create an array containing only even numbers from 1 to 50.
g=np.arange(0,50,2)
g

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [35]:
#Create an array containing multiples of 5 from 0 to 100.
h=np.arange(0,101,5)
h

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [37]:
#Find the maximum and minimum value in an array.
i=np.array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])
print("max",i.max())
print("min",i.min())

max 100
min 0


In [38]:
#Find the index position of the largest element.
i=np.array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])
print("max",i.max())
i1=i.argmax()
print("index position of the largest element : ",i1)

max 100
index position of the largest element :  20


In [ ]:
Sort an array in ascending order.
Reverse an array without using loops.
Perform element-wise addition of two arrays.
Perform subtraction, multiplication, and division on arrays.
Find the mean, median, and standard deviation of an array.
Find the sum of all rows and columns in a matrix.
Multiply two matrices using NumPy.
Find the transpose of a matrix.
Find the determinant of a matrix.

In [41]:
#Sort an array in ascending order.
j=np.random.randint(1,28,10)
j1=np.sort(j)
j1

array([ 2,  8,  8,  8, 17, 18, 19, 20, 23, 26], dtype=int32)

In [44]:
#Reverse an array without using loops.
k=np.array([ 2,  8,  8,  8, 17, 18, 19, 20, 23, 26])
k1=k[::-1]
k1

array([26, 23, 20, 19, 18, 17,  8,  8,  8,  2])

In [45]:
# Perform element-wise addition of two arrays.

l = np.array([1, 2, 3, 4, 5])
l1 = np.array([10, 20, 30, 40, 50])

l2 = l + l1
l2

array([11, 22, 33, 44, 55])

In [46]:
# Perform subtraction, multiplication, and division on arrays.

m = np.array([2, 4, 6, 8, 10])
m1 = np.array([1, 2, 3, 4, 5])

m2 = m - m1
m3 = m * m1
m4 = m / m1

print(m2)
print(m3)
print(m4)

[1 2 3 4 5]
[ 2  8 18 32 50]
[2. 2. 2. 2. 2.]


In [47]:

# Find the mean, median, and standard deviation of an array.

n = np.array([10, 20, 30, 40, 50])

n1 = np.mean(n)
n2 = np.median(n)
n3 = np.std(n)

print("Mean =", n1)
print("Median =", n2)
print("Standard Deviation =", n3)

Mean = 30.0
Median = 30.0
Standard Deviation = 14.142135623730951


In [48]:
# Find the sum of all rows and columns in a matrix.

o = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

o1 = np.sum(o, axis=1)   # row sum
o2 = np.sum(o, axis=0)   # column sum

print("Row Sum =", o1)
print("Column Sum =", o2)

Row Sum = [ 6 15 24]
Column Sum = [12 15 18]


In [49]:
# Multiply two matrices using NumPy.

p = np.array([[1, 2],
              [3, 4]])

p1 = np.array([[5, 6],
               [7, 8]])

p2 = np.dot(p, p1)

print(p2)

[[19 22]
 [43 50]]
